import {Colors} from 'react-native-paper';
import {highlightColor} from './helpers';

// export const secondary = '#0A7E8C';
export const mainText = '#373D3F';
export const accent = Colors.purple500;
export const secondary = Colors.indigo700;
export const headline = Colors.black;
export const text = Colors.black;
export const title = Colors.black;
export const background = Colors.white;
export const altBackground = Colors.grey100;
export const primary = '#ffffff';
export const primaryHighlight = highlightColor(primary, -20);
export const secondaryHighlight = highlightColor(secondary, -20);
export const muted = Colors.grey500;
export const gray = '#f6f6f6';
export const white = '#ffffff';
export const hightlightWhite = highlightColor(white, 20);
export const mutedIcon = Colors.grey500;
export const iconColor = Colors.grey300;
