export const SELECT_TRANSACTION = 'SELECT_TRANSACTION';
export const ACTION_TRANSACTION = 'ACTION_TRANSACTION';
export const ACTION_TRANSACTION_SUCCESS = 'REMOVE_TRANSACTION_SUCESS';
export const ACTION_TRANSACTION_FAILURE = 'ACTION_TRANSACTION_FAILURE';
